def return_all_implemented_tools():
    from tools.issues import (
        add_issue_comment_tool,
        create_issue_tool,
        get_issue_tool,
        list_issues_tool,
        search_issues_tool,
        update_issue_tool,
        get_issue_comments_tool,
    )
    from tools.pull_requests import (
    search_pull_requests_tool,
    list_pull_requests_tool,
    create_pull_request_tool,
    get_pull_request_tool,
    get_pull_request_diff_tool,
    get_pull_request_files_tool,
    get_pull_request_reviews_tool,
    update_pull_request_tool,
    merge_pull_request_tool,
    create_pending_pull_request_review_tool,
    add_pull_request_review_comment_to_pending_review_tool,
    delete_pending_pull_request_review_tool,
    submit_pending_pull_request_review_tool,
    create_and_submit_pull_request_review_tool,
    get_pull_request_status_tool,
    )

    from tools.repository_management import (
        get_file_contents_tool,
        create_branch_tool,
        create_repository_tool,
        get_file_tool,
        write_file_tool,
        delete_file_tool,
        push_files_tool,
        list_commits_tool,
        get_commit_tool,
        list_branches_tool,
        search_repositories_tool,
    )

    from tools.user import (
        list_notifications_tool,
        get_me_tool,
        search_users_tool,
    )

    return [
        list_notifications_tool,
        search_users_tool,
        list_issues_tool,
        update_issue_tool,
        add_issue_comment_tool,
        get_issue_tool,
        create_issue_tool,
        get_file_contents_tool,
        create_branch_tool,
        create_repository_tool,
        get_me_tool,
        get_file_tool,
        write_file_tool,
        delete_file_tool,
        push_files_tool,
        search_repositories_tool,
        list_commits_tool,
        get_commit_tool,
        list_branches_tool,
        search_issues_tool,
        get_issue_comments_tool,
        search_pull_requests_tool,
        list_pull_requests_tool,
        create_pull_request_tool,
        get_pull_request_tool,
        get_pull_request_diff_tool,
        get_pull_request_files_tool,
        get_pull_request_reviews_tool,
        update_pull_request_tool,
        merge_pull_request_tool,
        create_pending_pull_request_review_tool,
        add_pull_request_review_comment_to_pending_review_tool,
        delete_pending_pull_request_review_tool,
        submit_pending_pull_request_review_tool,
        create_and_submit_pull_request_review_tool,
        get_pull_request_status_tool,
    ]
